# Site settings
title: 1d20 Development
description: Web Development Company
brand: 1d20
email: 1d20dev@gmail.com
facebook_username: 1d20dev
github_username: 1d20
url: "https://1d20.github.io"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

plugins:
  - jekyll-seo-tag

#  - jekyll-compress-images

#compress_images:
#  images_path: "img/**/*.{gif,png,jpg,jpeg,svg}"